### ISSUE TITLE
Permission to create youtube video for this icon builder feature for global user helpful perpose

### ISSUE THREAD

**Issue by hareshkansara** [spilymp/ibo#10]
Hello There,

I have checked but not found way to communicate to owner of this repo. So i am writing here for asking your permission.

Because i can see this icon builder is very useful so i want to create youtube video so everyone can aware about this.

Could you please provide me permission @spilymp

**Comment by spilymp** [comment]
Hello,

thank you for your patience and interest in the project. I think you do not need (according to the license) my permission to make a video about this open source software, and there is already a video about this project: [LINK](https://www.youtube.com/watch?v=hRBuPFwVgsM) 
But thanks for the question and of course you/anyone have my permission to make a (YouTube) videos about this project. 

Feel free to add the link to your video on this issue, maybe in the future I will add a video section to the documentation. For now, I'll close this issue and wish you all the best.

**Comment by hareshkansara** [comment]
Thank you very much. Actually i have just created issue here to contact you. 

Alright thanks.
