### ISSUE TITLE
Tabler Icons do not work

### ISSUE THREAD

**Issue by Rad0van** [spilymp/ibo#12]
The URL to load from (https://unpkg.com/@tabler/icons@2.22.0/iconfont/tabler-icons.min.css) is no longer functioning. Replacing with the one from the docs (https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/tabler-icons.min.css) does not seem to make it work though. Not really sure what's wrong there.

**Comment by spilymp** [comment]
Thanks for the information and for using this project. I added the correct CDN link (and also updated some other icon packs). Tabler icons should work again. FYI: when I tested it, the CDN provide version 2.26 not the current version 2.27! I close the issue at this point. If this error occurs again or other errors, please open another issue.
