### ISSUE TITLE
Some icon type do not work again :-(

### ISSUE THREAD

**Issue by Rad0van** [spilymp/ibo#13]
Briefly tested here and these do not work:

- Font Awesome 5 Solid & Regular
- Font Awesome 5 Brands
- Tabler Icons

**Comment by spilymp** [comment]
Hello,

thank you very much for your patience and interest in the project. I could not find any problems during a quick test. Can you please provide an example for each font which is not working? Thanks in advance!

**Comment by Rad0van** [comment]
Here's some re-testing:
- Font Awesome 5 Solid & Regular - seems to work now
- Font Awesome 5 Brands - seems to work too
- Tabler Icons - cannot make this one work. Selected the first icon 123, have tried to use name, react name, HTML char, hex and even class from source "icon icon-tabler icon-tabler-123" None seems to work. But maybe I am just doing something wrong.

**Comment by spilymp** [comment]
Hello, 

thank you for your reply. For all the icon fonts you always have to use the css class and your mentioned CSS classes are not correct.

Please try the following:
Go to the icon generator website (https://spilymp.github.io/ibo/) to use the latest version, select the icon set "Tabler Icons", go to the provided tabler icons website, select the first icon ("123"), click "See more icon variants" and copy the css class to the icon generator. 

Where to find the css class on the tabler icon website:
![Image where to find CSS class on tabler icon website](https://github.com/spilymp/ibo/assets/5854430/0a84a200-6425-4d84-b701-bc8fa0fb2c54)

Final configuration for the icon generator:
![grafik](https://github.com/spilymp/ibo/assets/5854430/ce8f1502-8f80-4e86-b71a-8e52d8bfa52a)

**Comment by Rad0van** [comment]
Seems this is working. Don't know what class have I been trying. Thanks a lot!

**Comment by spilymp** [comment]
Happy to hear that it works now. I close this issue, if you encounter any other problems with the generator do not hesitate to open a new issue.
