### ISSUE TITLE
Several Icons Cannot be Generated

### ISSUE THREAD

**Issue by altela** [spilymp/ibo#6]
Several icons cannot be rendered and the outcome result is "blank".
Here's the example : 

![Screen Shot 2022-04-07 at 16 51 37](https://user-images.githubusercontent.com/68892527/162160581-3e3c84be-a52d-4094-9a99-8d746d4e9a3a.png)

the problem might be caused somewhere in `_getUnicodeAndFontWeight` method.

**Comment by spilymp** [comment]
Thank you for using this project! The icon you used was not yet included in the Bootstrap icon version (1.5) used in the project so far. I have now included the latest version (1.8) and your mentioned icon is now working. I close the issue at this point. If this error occurs again or other errors, please open another issue.

**Comment by altela** [comment]
Whoaa thank you for your feedback, it's now working great!
loved this project so much, it's very helpful. 
Thanks again!
