### ISSUE TITLE
Own Icon Usage

### ISSUE THREAD

**Issue by bosd** [spilymp/ibo#8]
Is there an option to use your own icon instead of the provided fonts.

Use case example:
There is an module made conform to the peppol standard. Would like to place the peppol logo on a odoo tile.

**Comment by spilymp** [comment]
Hello,

thank you very much for your patience and interest in the project. You can add any additional icon sets or your own icons locally or in a fork. For this, as also described in the documentation, you can pass either a valid CSS class (parameter "icon_class") or the character/icon (parameter "icon_text") directly to the icon builder. However, there will not be a generic way on the provided website to insert external icons, thank you for understanding.
